import { CapitalismPhase, HistoricalEvent, ProductionRegion, TradeRoute } from './types';

export const HISTORICAL_EVENTS: HistoricalEvent[] = [
  {
    id: 1,
    year: 1100,
    displayYear: "~1100-1500",
    title: "多中心的棉花世界 (Multipolar Origins)",
    locationName: "Gujarat, India",
    coordinates: { lat: 22.2587, lng: 71.1924 },
    phase: CapitalismPhase.ORIGINS,
    description: "在欧洲介入之前，棉花网络是区域性的。印度古吉拉特邦是当时世界的棉纺织中心，其产品向西流向中东和非洲，向东流向东南亚。这是一个基于技艺高超的工匠和村庄生产的体系。",
    impact: "早在工业革命几个世纪前，印度纺织品就已经统治了印度洋贸易网络。",
  },
  {
    id: 2,
    year: 1450,
    displayYear: "~1450",
    title: "阿兹特克的进贡 (Aztec Tribute)",
    locationName: "Tenochtitlan, Mexico",
    coordinates: { lat: 19.4326, lng: -99.1332 },
    phase: CapitalismPhase.ORIGINS,
    description: "在美洲，棉花同样神圣且重要。阿兹特克被征服的城邦必须以棉织幔帐和生棉作为贡品。这证明了在欧洲人到来之前，全球南方各地独立发展出了复杂的棉花经济。",
    impact: "展示了棉花在前殖民时代美洲经济和政治中的核心地位。",
  },
  {
    id: 3,
    year: 1492,
    displayYear: "1492",
    title: "哥伦布到达美洲 (Discovery of Americas)",
    locationName: "Bahamas",
    coordinates: { lat: 25.0343, lng: -77.3963 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "哥伦布发现美洲土著拥有棉花，这激发了欧洲人的贪婪。这是“战争资本主义”的开端：通过武力掠夺土地和奴役原住民，欧洲人为建立跨大西洋的贸易网络奠定了基础。",
    keyFigure: "Christopher Columbus",
    impact: "开启了全球范围内土地掠夺和资源重组的序幕。",
  },
  {
    id: 4,
    year: 1600,
    displayYear: "1600",
    title: "东印度公司成立 (EIC Established)",
    locationName: "London, UK",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "英国东印度公司成立，标志着武装贸易的制度化。欧洲商人不再满足于作为中间商，而是开始通过军事力量控制贸易路线，强行插入亚洲成熟的棉花网络。",
    impact: "国家力量与商业资本深度结合，推行武装贸易。",
  },
  {
    id: 5,
    year: 1721,
    displayYear: "1721",
    title: "卡利科法案 (The Calico Acts)",
    locationName: "London, UK",
    coordinates: { lat: 51.5074, lng: -0.11 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "面对廉价且优质的印度棉布的冲击，英国颁布法案禁止进口印花棉布。这种保护主义政策旨在摧毁印度的竞争优势，并为英国本土幼稚的纺织工业提供成长空间。",
    impact: "通过国家立法干预市场，为英国工业革命创造了温室环境。",
  },
  {
    id: 6,
    year: 1750,
    displayYear: "1750s",
    title: "奴隶贸易的枢纽 (The Slave Coast)",
    locationName: "Ouidah, Benin",
    coordinates: { lat: 6.3630, lng: 2.0851 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "为了满足美洲种植园对劳动力的需求，数百万非洲人被贩卖。西非沿海成为战争资本主义残酷逻辑的中心，人类身体成为换取棉花等商品的货币。",
    impact: "没有奴隶制提供的廉价劳动力，全球棉花帝国的早期扩张是不可能的。",
  },
  {
    id: 7,
    year: 1784,
    displayYear: "1784",
    title: "工业资本主义的诞生 (Quarry Bank Mill)",
    locationName: "Manchester, UK",
    coordinates: { lat: 53.4808, lng: -2.2426 },
    phase: CapitalismPhase.INDUSTRIAL_CAPITALISM,
    description: "塞缪尔·格雷格建立阔里班克纺纱厂。这是新技术（水力纺纱机）、受薪劳工管理制度和全球供应链（美洲棉花）的结合体，标志着工厂制度的诞生。",
    keyFigure: "Samuel Greg",
    impact: "生产效率剧增，棉花制造业中心开始从亚洲不可逆转地转移到欧洲。",
  },
  {
    id: 8,
    year: 1791,
    displayYear: "1791",
    title: "海地革命 (Haitian Revolution)",
    locationName: "Saint-Domingue, Haiti",
    coordinates: { lat: 19.1400, lng: -72.2000 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "当时世界上最重要的棉花和糖产地的奴隶起义，摧毁了当地的种植园经济。这迫使欧洲资本家寻找新的原料产地，最终将目光锁定在美国南方。",
    impact: "加勒比供应的中断直接加速了美国南方作为棉花王国的崛起。",
  },
  {
    id: 9,
    year: 1793,
    displayYear: "1793",
    title: "轧棉机的发明 (The Cotton Gin)",
    locationName: "Georgia, USA",
    coordinates: { lat: 32.1656, lng: -82.9001 },
    phase: CapitalismPhase.INDUSTRIAL_CAPITALISM,
    description: "伊莱·惠特尼发明轧棉机，解决了短绒棉脱籽的难题。这项技术突破使得美国内陆广阔的土地可以种植棉花，直接导致了奴隶制在美国南方的急剧扩张。",
    keyFigure: "Eli Whitney",
    impact: "技术与奴隶制的结合，使美国在几十年内垄断了全球原棉供应。",
  },
  {
    id: 10,
    year: 1803,
    displayYear: "1800-1830s",
    title: "血泪之路 (Trail of Tears)",
    locationName: "Mississippi Delta, USA",
    coordinates: { lat: 32.7469, lng: -90.5063 },
    phase: CapitalismPhase.WAR_CAPITALISM,
    description: "为了扩大棉花种植，美国政府强行驱逐了乔克托、切罗基等原住民部落。这是战争资本主义在国内的延续——清空土地上的原住民，代之以奴隶种植园。",
    impact: "通过国家暴力为棉花资本主义腾出了最肥沃的土地（密西西比三角洲）。",
  },
  {
    id: 11,
    year: 1820,
    displayYear: "1820s",
    title: "利物浦：贸易神经中枢 (Liverpool)",
    locationName: "Liverpool, UK",
    coordinates: { lat: 53.4084, lng: -2.9916 },
    phase: CapitalismPhase.INDUSTRIAL_CAPITALISM,
    description: "利物浦成为连接美国种植园和曼彻斯特工厂的枢纽。棉花交易所制定标准、提供信贷，不仅控制实物贸易，更控制了全球棉花金融。",
    impact: "商人们在此不仅交易棉花，更是在交易全球经济的命运。",
  },
  {
    id: 12,
    year: 1823,
    displayYear: "1823",
    title: "洛厄尔工厂 (Lowell Mills)",
    locationName: "Massachusetts, USA",
    coordinates: { lat: 42.6334, lng: -71.3162 },
    phase: CapitalismPhase.INDUSTRIAL_CAPITALISM,
    description: "弗朗西斯·卡伯特·洛厄尔将英国的动力织布机技术“偷”回美国，建立了综合纺织厂。美国北部开始工业化，通过加工南方的奴隶棉花积累财富。",
    impact: "工业资本主义跨越大西洋，美国开始挑战英国的制造地位。",
  },
  {
    id: 13,
    year: 1850,
    displayYear: "1850s",
    title: "欧洲大陆的工业化 (Mulhouse)",
    locationName: "Mulhouse, France",
    coordinates: { lat: 47.7508, lng: 7.3359 },
    phase: CapitalismPhase.INDUSTRIAL_CAPITALISM,
    description: "被称为“法国的曼彻斯特”，阿尔萨斯地区的米卢斯成为欧洲大陆棉纺织业的中心。工业资本主义模式在欧洲大陆复制，加剧了对原棉的竞争。",
    impact: "棉花工业成为欧洲各国迈向现代化的必经之路。",
  },
  {
    id: 14,
    year: 1861,
    displayYear: "1861",
    title: "美国内战与全球大恐慌 (The Cotton Famine)",
    locationName: "South Carolina, USA",
    coordinates: { lat: 33.8361, lng: -81.1637 },
    phase: CapitalismPhase.GLOBAL_RECONSTRUCTION,
    description: "内战爆发导致美国对欧棉花出口中断。这场“全球大恐慌”暴露了世界经济对美国奴隶棉花的极度依赖，迫使欧洲列强疯狂寻找替代来源。",
    impact: "一场震荡世界的资本主义危机，也是重塑全球劳动力体系的转折点。",
  },
  {
    id: 15,
    year: 1863,
    displayYear: "1863",
    title: "孟买的繁荣 (Bombay Boom)",
    locationName: "Mumbai, India",
    coordinates: { lat: 18.9863, lng: 72.8432 },
    phase: CapitalismPhase.GLOBAL_RECONSTRUCTION,
    description: "由于美国供应切断，印度棉花价格飙升。孟买商人获得了巨额财富，城市面貌因“棉花钱”而改变。但这繁荣是短暂的，也导致了后来的粮食危机。",
    impact: "全球供应链重组的直接受益者，促使英国加速对印度的基础设施建设。",
  },
  {
    id: 16,
    year: 1865,
    displayYear: "1865",
    title: "沙俄进军中亚 (Russian Tashkent)",
    locationName: "Tashkent, Uzbekistan",
    coordinates: { lat: 41.2995, lng: 69.2401 },
    phase: CapitalismPhase.GLOBAL_RECONSTRUCTION,
    description: "为了摆脱对美国棉花的依赖，沙俄帝国征服了塔什干，并开始在中亚大规模推广棉花种植。这是国家主导的帝国主义项目，旨在建立自给自足的棉花基地。",
    impact: "中亚从此被改造成单一的棉花产地，影响延续至今。",
  },
  {
    id: 17,
    year: 1882,
    displayYear: "1882",
    title: "英国占领埃及 (Occupation of Egypt)",
    locationName: "Cairo, Egypt",
    coordinates: { lat: 30.0444, lng: 31.2357 },
    phase: CapitalismPhase.GLOBAL_RECONSTRUCTION,
    description: "英国为了确保苏伊士运河安全及棉花供应，军事占领了埃及。埃及的农业被重组以服务兰开夏的纺纱厂，农民被迫种植长绒棉。",
    impact: "全球乡村（Global Countryside）被强行整合进帝国主义的工业体系。",
  },
  {
    id: 18,
    year: 1896,
    displayYear: "1896",
    title: "殖民地的实验 (Colonial Togo)",
    locationName: "Lome, Togo",
    coordinates: { lat: 6.1375, lng: 1.2125 },
    phase: CapitalismPhase.GLOBAL_RECONSTRUCTION,
    description: "德国殖民者试图在多哥建立“科学的”棉花种植园，甚至引入美国南方的黑人专家。欧洲列强试图在非洲复制美国南方的成功，但多以失败告终。",
    keyFigure: "Tuskegee Experts",
    impact: "通过殖民国家强力推行棉花种植，试图打破美国垄断。",
  },
  {
    id: 19,
    year: 1905,
    displayYear: "1905",
    title: "国货运动 (Swadeshi Movement)",
    locationName: "Calcutta, India",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "印度民族主义者号召抵制英国布，回归土布（Khadi）。甘地将纺车作为反抗殖民统治的象征。棉花不再只是商品，成为了政治斗争的武器。",
    keyFigure: "Mahatma Gandhi",
    impact: "标志着全球南方开始夺回对棉花生产和制造的控制权。",
  },
  {
    id: 20,
    year: 1920,
    displayYear: "1920s",
    title: "日本的崛起 (Rise of Japan)",
    locationName: "Osaka, Japan",
    coordinates: { lat: 34.6937, lng: 135.5023 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "利用廉价的女工和创新的丰田自动织机，日本纺织品开始在国际市场上击败英国产品。大阪被称为“东洋的曼彻斯特”。",
    impact: "亚洲工业化国家首次在棉花制造领域超越西方列强。",
  },
  {
    id: 21,
    year: 1930,
    displayYear: "1930s",
    title: "上海纱厂 (Shanghai Mills)",
    locationName: "Shanghai, China",
    coordinates: { lat: 31.2304, lng: 121.4737 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "中国本土企业家和外资在上海建立了庞大的纺织工业基地。尽管战乱频仍，中国开始重新夺回其作为棉花大国的历史地位。",
    impact: "全球棉花产业重心加速向亚洲回流。",
  },
  {
    id: 22,
    year: 1960,
    displayYear: "1960s-80s",
    title: "咸海的消亡 (Aral Sea Disaster)",
    locationName: "Aral Sea, Uzbekistan",
    coordinates: { lat: 45.0000, lng: 60.0000 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "苏联为了棉花自给自足，过度截流阿姆河和锡尔河灌溉棉田，导致世界第四大湖泊咸海几乎干涸。这是棉花单一作物种植造成的最严重环境灾难。",
    impact: "揭示了工业化棉花种植对环境的毁灭性代价。",
  },
  {
    id: 23,
    year: 1963,
    displayYear: "1963",
    title: "利物浦交易所关闭 (End of Dominance)",
    locationName: "Liverpool, UK",
    coordinates: { lat: 53.4084, lng: -2.9916 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "利物浦棉花交易所的关闭象征着欧洲长达两个世纪的统治终结。棉花帝国完成了它的全球循环，生产中心彻底回到了全球南方。",
    impact: "欧洲失去了对棉花帝国的控制权。",
  },
  {
    id: 24,
    year: 2000,
    displayYear: "2000s",
    title: "底层的竞赛 (Race to the Bottom)",
    locationName: "Dhaka, Bangladesh",
    coordinates: { lat: 23.8103, lng: 90.4125 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "全球成衣制造业转移到劳动力成本最低的国家。孟加拉国成为世界制衣工厂，工人（主要是女性）在极其恶劣的条件下工作（如Rana Plaza惨案），以满足西方的快时尚需求。",
    impact: "虽然生产回到了南方，但由于品牌和零售商掌握了利润，剥削的形式变得更加隐蔽。",
  },
  {
    id: 25,
    year: 2013,
    displayYear: "Modern Era",
    title: "补贴与高科技 (Subsidized Empire)",
    locationName: "Lubbock, Texas",
    coordinates: { lat: 33.5779, lng: -101.8552 },
    phase: CapitalismPhase.RETURN_OF_SOUTH,
    description: "尽管制造业转移，美国通过巨额政府补贴和高度机械化的精准农业，依然是世界上最大的棉花出口国。Lubbock是这个高科技农业帝国的中心。",
    impact: "在自由贸易的幌子下，国家补贴扭曲了全球市场，使得西非等地的贫穷棉农难以生存。",
  }
];

export const PRODUCTION_REGIONS: ProductionRegion[] = [
  // Origins
  { id: 'p-ind-guj', phase: CapitalismPhase.ORIGINS, coordinates: [71.1924, 22.2587], name: "Gujarat (Weaving)", radius: 10 },
  { id: 'p-ind-ben', phase: CapitalismPhase.ORIGINS, coordinates: [88.3639, 23.0000], name: "Bengal (Muslin)", radius: 10 },
  { id: 'p-chn-yan', phase: CapitalismPhase.ORIGINS, coordinates: [120.5000, 31.0000], name: "Yangtze Delta", radius: 8 },
  { id: 'p-mex-teh', phase: CapitalismPhase.ORIGINS, coordinates: [-97.5000, 18.5000], name: "Tehuacan", radius: 6 },
  
  // War Capitalism
  { id: 'p-car-dom', phase: CapitalismPhase.WAR_CAPITALISM, coordinates: [-72.0000, 19.0000], name: "Saint-Domingue", radius: 8 },
  { id: 'p-bra-rec', phase: CapitalismPhase.WAR_CAPITALISM, coordinates: [-35.0000, -8.0000], name: "Pernambuco", radius: 8 },
  { id: 'p-ind-dec', phase: CapitalismPhase.WAR_CAPITALISM, coordinates: [77.0000, 16.0000], name: "Deccan Plateau", radius: 12 },

  // Industrial Capitalism
  { id: 'p-usa-south', phase: CapitalismPhase.INDUSTRIAL_CAPITALISM, coordinates: [-88.0000, 33.0000], name: "The Cotton Belt", radius: 25 },
  
  // Global Reconstruction
  { id: 'p-egy-del', phase: CapitalismPhase.GLOBAL_RECONSTRUCTION, coordinates: [31.0000, 30.5000], name: "Nile Delta", radius: 8 },
  { id: 'p-ind-ber', phase: CapitalismPhase.GLOBAL_RECONSTRUCTION, coordinates: [77.5000, 21.0000], name: "Berar", radius: 10 },
  { id: 'p-uzb-fer', phase: CapitalismPhase.GLOBAL_RECONSTRUCTION, coordinates: [71.0000, 40.5000], name: "Fergana Valley", radius: 7 },
  
  // Return of South
  { id: 'p-chn-xin', phase: CapitalismPhase.RETURN_OF_SOUTH, coordinates: [85.0000, 41.0000], name: "Xinjiang", radius: 12 },
  { id: 'p-usa-tex', phase: CapitalismPhase.RETURN_OF_SOUTH, coordinates: [-101.8, 33.5], name: "Texas High Plains", radius: 10 },
  { id: 'p-afr-wst', phase: CapitalismPhase.RETURN_OF_SOUTH, coordinates: [2.0000, 11.0000], name: "West Africa", radius: 15 },
];

export const TRADE_ROUTES: TradeRoute[] = [
  // Origins
  { id: 'r-ind-red', phase: CapitalismPhase.ORIGINS, start: [70, 20], end: [45, 12], type: 'textiles' },
  { id: 'r-ind-sea', phase: CapitalismPhase.ORIGINS, start: [80, 15], end: [100, 3], type: 'textiles' },
  
  // War Capitalism (Triangle Trade elements)
  { id: 'r-tri-slv', phase: CapitalismPhase.WAR_CAPITALISM, start: [2, 6], end: [-40, -10], type: 'slaves', label: "Middle Passage" },
  { id: 'r-tri-slv2', phase: CapitalismPhase.WAR_CAPITALISM, start: [2, 6], end: [-75, 18], type: 'slaves' },
  { id: 'r-tri-cot', phase: CapitalismPhase.WAR_CAPITALISM, start: [-75, 20], end: [-5, 50], type: 'cotton', label: "Raw Cotton" },
  { id: 'r-tri-tex', phase: CapitalismPhase.WAR_CAPITALISM, start: [75, 20], end: [0, 51], type: 'textiles', label: "Calicoes" },
  
  // Industrial Capitalism
  { id: 'r-liv-no', phase: CapitalismPhase.INDUSTRIAL_CAPITALISM, start: [-90, 29], end: [-3, 53], type: 'cotton', label: "Cotton Highway" },
  { id: 'r-man-exp', phase: CapitalismPhase.INDUSTRIAL_CAPITALISM, start: [-3, 53], end: [72, 18], type: 'textiles', label: "Finished Cloth" },
  
  // Global Reconstruction
  { id: 'r-bom-liv', phase: CapitalismPhase.GLOBAL_RECONSTRUCTION, start: [72, 18], end: [-3, 53], type: 'cotton' },
  { id: 'r-egy-liv', phase: CapitalismPhase.GLOBAL_RECONSTRUCTION, start: [30, 31], end: [-3, 53], type: 'cotton' },
  
  // Return of South
  { id: 'r-usa-chn', phase: CapitalismPhase.RETURN_OF_SOUTH, start: [-118, 33], end: [122, 31], type: 'cotton' },
  { id: 'r-chn-usa', phase: CapitalismPhase.RETURN_OF_SOUTH, start: [122, 31], end: [-122, 37], type: 'textiles', label: "Fast Fashion" },
  { id: 'r-ban-eur', phase: CapitalismPhase.RETURN_OF_SOUTH, start: [90, 23], end: [10, 50], type: 'textiles' },
];

export const PHASE_COLORS: Record<CapitalismPhase, string> = {
  [CapitalismPhase.ORIGINS]: "#10b981", // Emerald
  [CapitalismPhase.WAR_CAPITALISM]: "#ef4444", // Red (Violence)
  [CapitalismPhase.INDUSTRIAL_CAPITALISM]: "#3b82f6", // Blue (Industry)
  [CapitalismPhase.GLOBAL_RECONSTRUCTION]: "#f59e0b", // Amber (Transition)
  [CapitalismPhase.RETURN_OF_SOUTH]: "#8b5cf6", // Violet (Shift)
};
